### ISSUE TITLE
Orphan comment?

### ISSUE THREAD

**Issue by ybgwon** [thanhvg/emacs-virtual-comment#2]
Hi !

```
#define LIST_HEAD(name) \
	struct list_head name = LIST_HEAD_INIT(name)

 static inline void INIT_LIST_HEAD(struct list_head *list)
{
	WRITE_ONCE(list->next, list);
	list->prev = list;
}
```
When I wanted to comment  INIT_LIST_HEAD function,
My cursor positioned above "static inline  void ..." line.
and I ran virtual-comment-make. 
```
#define LIST_HEAD(name) \
	struct list_head name = LIST_HEAD_INIT(name)
// This is place where comment created
<- Here is cursor position and where i want to place comment.
 static inline void INIT_LIST_HEAD(struct list_head *list)
{
	WRITE_ONCE(list->next, list);
	list->prev = list;
}
```
So I wanted to move my comment below but I could not.
I could not edit or delete.

**Comment by thanhvg** [comment]
Yeah you put a comment on an empty line. I'll see if I can have a fix to make sure we can delete or edit it.

**Comment by thanhvg** [comment]
I added the fix, let me know if it works, thanks.

**Comment by ybgwon** [comment]
I haven't tested it long, It works.
Thank you.
