### ISSUE TITLE
Error while loading virtual comments

### ISSUE THREAD

**Issue by thornjad** [thanhvg/emacs-virtual-comment#4]
I love the concept of this, but I'm running into an error when trying to load a file which has associate virtual comments:

```
virtual-comment--get-project: Invalid object argument: Git, "~/src/example_project/"
```

As far as I can tell so far, this happens anytime I try to load a file which should have virtual comments. Any pointers and/or do you need any more information? It doesn't appear to generate a backtrace, just the message.

**Comment by thanhvg** [comment]
What's the version of emacs?

Can you `eval` (`M-:`) on the file you are having problem with and show me the output of these:

`(project-current)`

`virtual-comment--project`

**Comment by thornjad** [comment]
My Emacs is built from master, reports as 29.0.50, but its been a few weeks since I last compiled, if you suspect it could be an Emacs issue I can pull and recompile.

`(project-current)` on a python file in which I've made a couple virtual comments returns `(vc Git "~/src/example_project/")`

`virtual-comment--project` is `nil`

I've also noticed this same thing happens with `virtual-comment-show` but this time with a stack trace! **Edited** to calling it without Counsel

```
Debugger entered--Lisp error: (wrong-type-argument stringp (Git "~/src/example_project/"))
  file-truename((Git "~/src/example_project/"))
  virtual-comment--get-buffer-file-name()
  virtual-comment-show()
  #<subr eval-expression>((virtual-comment-show) nil nil 127)
  apply(#<subr eval-expression> ((virtual-comment-show) nil nil 127))
  eval-expression((virtual-comment-show) nil nil 127)
  funcall-interactively(eval-expression (virtual-comment-show) nil nil 127)
  command-execute(eval-expression)
```

**Comment by thornjad** [comment]
Also, `default-directory` on that file is `"/Users/jmt/src/example_project/server/handlers/"`

**Comment by thanhvg** [comment]
Oh so `project-current` has changed in emacs 29.  `emacs-virtual-comment` does not support 29 yet.

I expected it to return `(vc . "~/src/example_project/")` This is what emacs 26, 27 and 28 do. 

Can you try emacs 27 or 28?

**Comment by thornjad** [comment]
Ah, I see, makes sense. I don't have time at the moment to try out an earlier version, but I believe you. Would it be enough to replace `(cdr (project-current))` with `(caddr (project-current))` when Emacs version is >= 29? Or is it more nuanced than that? i.e. Is it always a 3-part list?

If its not too much more complicated, I wouldn't mind making a PR in the next couple days to implement that.

**Comment by thanhvg** [comment]
PRs are welcome but they must support current official emacs versions from 26 to 28. 

The change you suggest will work with 29 only. I am thinking about replacing `(cdr (project-current))` with `(project-root (project-current))` which may be more compatible across versions.

**Comment by thanhvg** [comment]
Hey I added a tentative fix for this to master, can you try it pls.

**Comment by thornjad** [comment]
It works!! And that fix is pretty much exactly what I was thinking! Thank you!
